# Configuración Netlify para TuPatrimonio
# Habilita detección automática de ubicación y redirects por país

[build]
  # Configuración de build para marketing app por defecto
  command = "npm run build:marketing"
  publish = "apps/marketing/.next"
  
  # Variables de entorno para build
  [build.environment]
    NODE_VERSION = "20"
    NEXT_TELEMETRY_DISABLED = "1"

# Headers globales con información de geolocalización
[[headers]]
  for = "/*"
  [headers.values]
    # Headers de seguridad
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Netlify agrega automáticamente estos headers de geolocalización:
    # x-nf-country-code - Código ISO del país (CL, MX, CO)
    # x-nf-geo-city - Ciudad del usuario  
    # x-nf-geo-subdivision-1-iso-code - Región/Estado

# Redirects específicos por país para marketing (backup de edge functions)
# Solo se ejecutan si las edge functions fallan

# Firmas Electrónicas
[[redirects]]
  from = "/firmas-electronicas"
  to = "/cl/firmas-electronicas"
  status = 302
  country = ["CL"]

[[redirects]]
  from = "/firmas-electronicas"
  to = "/mx/firmas-electronicas" 
  status = 302
  country = ["MX"]

[[redirects]]
  from = "/firmas-electronicas"
  to = "/co/firmas-electronicas"
  status = 302
  country = ["CO"]

# Notaría Digital
[[redirects]]
  from = "/notaria-digital"
  to = "/cl/notaria-digital"
  status = 302
  country = ["CL"]

[[redirects]]
  from = "/notaria-digital"
  to = "/mx/notaria-digital"
  status = 302
  country = ["MX"]

[[redirects]]
  from = "/notaria-digital"
  to = "/co/notaria-digital"
  status = 302
  country = ["CO"]

# Verificación de Identidad
[[redirects]]
  from = "/verificacion-identidad"
  to = "/cl/verificacion-identidad"
  status = 302
  country = ["CL"]

[[redirects]]
  from = "/verificacion-identidad"
  to = "/mx/verificacion-identidad"
  status = 302
  country = ["MX"]

[[redirects]]
  from = "/verificacion-identidad"
  to = "/co/verificacion-identidad"
  status = 302
  country = ["CO"]

# Precios
[[redirects]]
  from = "/precios"
  to = "/cl/precios"
  status = 302
  country = ["CL"]

[[redirects]]
  from = "/precios"
  to = "/mx/precios"
  status = 302
  country = ["MX"]

[[redirects]]
  from = "/precios"
  to = "/co/precios"
  status = 302
  country = ["CO"]

# Fallback redirects (si no se detecta país soportado)
[[redirects]]
  from = "/firmas-electronicas"
  to = "/cl/firmas-electronicas"
  status = 302

[[redirects]]
  from = "/notaria-digital"
  to = "/cl/notaria-digital"
  status = 302

[[redirects]]
  from = "/verificacion-identidad"
  to = "/cl/verificacion-identidad"
  status = 302

[[redirects]]
  from = "/precios"
  to = "/cl/precios"
  status = 302

# Configuración para Edge Functions
[[edge_functions]]
  function = "country-redirect"
  path = "/firmas-electronicas"

[[edge_functions]]
  function = "country-redirect"
  path = "/notaria-digital"

[[edge_functions]]
  function = "country-redirect"
  path = "/verificacion-identidad"

[[edge_functions]]
  function = "country-redirect"
  path = "/precios"

# Headers específicos para la función de detección
[[headers]]
  for = "/.netlify/functions/detect-country"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Cache-Control = "public, max-age=300"

# =====================================================
# CONFIGURACIÓN POR CONTEXTS - APPS MÚLTIPLES
# =====================================================

# Context para WEB APP (app.tupatrimonio.app)
# Usar en Site 2 de Netlify
[context.web]
  command = "npm run build:web"
  publish = "apps/web/.next"
  
  [context.web.environment]
    NODE_VERSION = "20"
    NEXT_TELEMETRY_DISABLED = "1"

# Context para MARKETING (tupatrimonio.app)  
# Usar en Site 1 de Netlify
[context.marketing]
  command = "npm run build:marketing"
  publish = "apps/marketing/.next"
  
  [context.marketing.environment]
    NODE_VERSION = "20"
    NEXT_TELEMETRY_DISABLED = "1"

# Context para DEVELOPMENT (branches de desarrollo)
[context.dev]
  command = "npm run build:marketing"
  publish = "apps/marketing/.next"

# Context para BRANCH-DEPLOY (cualquier branch que no sea main)
[context.branch-deploy]
  command = "npm run build:marketing"
  publish = "apps/marketing/.next"

# =====================================================
# HEADERS ESPECÍFICOS PARA WEB APP
# =====================================================

# Headers para proteger dashboard (solo context.web)
[[headers]]
  for = "/dashboard/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "private, no-cache, no-store"

[[headers]]
  for = "/login/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

# =====================================================
# REDIRECTS PARA WEB APP (Solo Site 2)
# =====================================================

# Redirects de conveniencia para auth
[[redirects]]
  from = "/signin"
  to = "/login"
  status = 301

[[redirects]]
  from = "/signup" 
  to = "/login"
  status = 301

# Redirect inteligente desde raíz
[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 200
  conditions = {Cookie = ["sb-*"]}

# Fallback al login si no hay sesión
[[redirects]]
  from = "/"
  to = "/login"
  status = 200
